# Generated by Django 3.1.2 on 2020-10-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20201008_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Installation_number', models.IntegerField(default=0)),
                ('InstallDate', models.DateField(auto_now_add=True)),
                ('RenewDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('AmountReceived', models.FloatField(default=0)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
