# Generated by Django 3.1.2 on 2020-10-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_installduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Customer',
            new_name='CustomerI',
        ),
    ]
