# Generated by Django 3.1.2 on 2020-10-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20201010_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='CustomerI',
            new_name='CustomerName',
        ),
    ]
