# Generated by Django 3.1.2 on 2020-10-12 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20201012_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='AmountReceived',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='InstallDuration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Installation_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='TotalAmount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
