# Generated by Django 3.1.2 on 2020-10-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201012_2043'),
        ('subscription', '0011_auto_20201013_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='CustomerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer'),
        ),
    ]
