# Generated by Django 3.1.2 on 2020-10-21 12:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201012_2043'),
        ('subscription', '0012_auto_20201013_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='CustomerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='customer.customer'),
        ),
        migrations.CreateModel(
            name='Renew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstallDuration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('RenewDate', models.DateField()),
                ('ExpiryDate', models.DateField()),
                ('TotalAmount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('AmountReceived', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('RemainingAmount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('Subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='customer.customer')),
            ],
        ),
    ]
