# Generated by Django 3.1.2 on 2020-10-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20201021_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renew',
            name='Subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='subscription.subscription'),
        ),
    ]
