# Generated by Django 3.1.2 on 2020-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Address1', models.CharField(max_length=150)),
                ('Address2', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=20)),
                ('Zone', models.CharField(max_length=100)),
                ('PhoneNo', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Contact_Person', models.CharField(max_length=100)),
                ('Contact_Person_MobileNo', models.CharField(max_length=15)),
                ('Contact_Person_Email', models.CharField(max_length=100)),
            ],
        ),
    ]
