# Generated by Django 3.1.2 on 2020-10-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201008_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
