# Generated by Django 3.1.2 on 2020-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201012_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
