# Generated by Django 3.1.2 on 2020-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201012_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ClientID',
            field=models.CharField(default='', max_length=10),
        ),
    ]
